version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ushios/dmm-clawrer-go
    docker:
      - image: golang:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install Docker client
          command: |
            set -x
            VER="17.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: check docker version
          command: |
            docker version
      - run:
          name: build docker image
          command: |
            docker build -t app .
      - run:
          name: run test
          command: |
            docker run -e "TEST_DMM_API_ID=${TEST_DMM_API_ID}" -e "TEST_DMM_AFFILIATE_ID=${TEST_DMM_AFFILIATE_ID}"  app go test ./...
